### PR TITLE
Update readme.de.md

### PR DESCRIPTION
**Pull request by jonathanpross**

### CODE REVIEW

**Comment by HJK181** [comment]
Why did you choose to hide the Youtuble player controls? This way the user can't control the volume or switch to fullscreen mode....
I'd suggest to embed it like this:

```
<iframe width="560" height="315" src="https://www.youtube.com/embed/yiPe1gTCtbs" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
```

**Comment by jonathanpross** [comment]
Yes, that’s fine. My intention was to keep the YouTube suggestions from showing. However, I had no way of previewing what the final version would look like once deployed.

Please embed as you suggest below.

Thanks

**Comment by HJK181** [comment]
You should visit https://stackedit.io/app# and paste your markup on the left hand side. Than you will "most probably" see the result as it will be displayed in our UI. Could you please adjust all files as it's your Pull Request ? :)

**Comment by jonathanpross** [comment]
Yes. I will adjust them. Thanks for the tip!

**Review by jonathanpross — COMMENTED** [review]
changed to include user controls.

**Pull request merged**
